cloud: Support executing code on errors
Add support for specifying code to be executed on command errors,
detected with 'set -e'. Enable 'set -E' to propagate the 'ERR' trap to
all functions and subshells automatically, so that they don't have to
explicitly set it themselves, but make sure to not execute code from
other shells, when each shell executes the trap.

diff --git a/cloud b/cloud
--- a/cloud
+++ b/cloud
@@ -10,7 +10,7 @@
 #   - no output should be produced unless something fails;
 #   - no error/message output on stdout, only stderr.
 
-set -euCo pipefail
+set -eEuCo pipefail
 shopt -s extglob
 
 # The directory where all temporary files should be created
@@ -24,6 +24,43 @@ function _cleanup() {
 
 # Cleanup on exit
 trap _cleanup EXIT
+
+# The list of pairs of shell PIDs and commands to be executed on error exits
+# from the corresponding shells, separated by a colon.
+declare -a ATERR=()
+
+# Execute "aterr" commands belonging to the current shell, in reverse order.
+function aterr_exec()
+{
+    declare i
+    for ((i = ${#ATERR[@]} - 1; i >= 0; i--)); do
+        if [ "${ATERR[i]%%:*}" == "$BASHPID" ]; then
+            eval "${ATERR[i]#*:}"
+        fi
+    done
+}
+
+# Execute aterr_exec on error exit enabled with "set -e".
+# Expect "set -E" propagating the ERR trap everywhere.
+trap aterr_exec ERR
+
+# Push a command to the stack of "aterr" commands. The command will be
+# executed on error exit from the current shell only.
+# Args: command
+function aterr_push()
+{
+    declare -r command="$1"; shift
+    ATERR+=("$BASHPID:$command")
+}
+
+# Pop the last command pushed to the stack of "aterr" commands.
+# Only pops the command if it was pushed by the same shell.
+function aterr_pop()
+{
+    if [ "${ATERR[-1]%%:*}" == "$BASHPID" ]; then
+        unset ATERR[-1]
+    fi
+}
 
 # "true" if verbose output is enabled, "false" otherwise
 declare VERBOSE="false"
