Actions: Add deployment check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -87,3 +87,48 @@ jobs:
               }
       - name: Validate test catalog
         run: kcidb-tests-validate --urls < tests.yaml
+
+  check_deployment:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check credentials
+        env:
+          STAGING_GCLOUD_PROJECT: ${{ secrets.STAGING_GCLOUD_PROJECT }}
+          STAGING_GCLOUD_SA_KEY: ${{ secrets.STAGING_GCLOUD_SA_KEY }}
+        run: |
+          # Check credentials
+          CREDENTIALS_PRESENT=true
+          function check() {
+            if eval "test -z \"\$$1\""; then
+              echo "$1 secret is missing." >&2
+              CREDENTIALS_PRESENT=false
+            fi
+          }
+          check STAGING_GCLOUD_PROJECT
+          check STAGING_GCLOUD_SA_KEY
+          if "$CREDENTIALS_PRESENT"; then
+            echo "All required credentials are present, continuing." >&2
+          else
+            echo "Required credentials are missing, aborting." >&2
+          fi
+          "$CREDENTIALS_PRESENT"
+      - uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
+      - name: Install
+        run: |
+          python -m pip install --upgrade pip setuptools
+          pip3 install --upgrade '.[dev]'
+      - name: Setup Google Cloud SDK
+        uses: google-github-actions/setup-gcloud@master
+        with:
+          project_id: ${{ secrets.STAGING_GCLOUD_PROJECT }}
+          service_account_key: ${{ secrets.STAGING_GCLOUD_SA_KEY }}
+          export_default_credentials: true
+      - name: Deploy and Withdraw
+        run: |
+          ./cloud deploy kernelci-staging "gh_run_${{ github.run_id }}" --verbose --smtp-password-file=<(echo foobar) || status="$?"
+          ./cloud withdraw kernelci-staging "gh_run_${{ github.run_id }}" --verbose
+          exit "${status:-0}"
